trigger:
- main

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)    
    steps:
    - task: DockerCompose@0
      displayName: Build services
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'dockerhub'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
        action: 'Build services'
    - task: DockerCompose@0
      displayName: Push services
      inputs:
        containerregistrytype: 'Container Registry'
        repository: 'unifique'
        dockerRegistryEndpoint: 'dockerhub'        
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'
    