trigger:
- main

variables:
  vmImageName: 'ubuntu-latest'
  tag: '$(Build.BuildId)'
  ProjetcName: 'sidneyevpereira/unifique:$(Build.BuildId)'  

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)    
    steps:    

    - task: DockerCompose@0
      displayName: Build services
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'dockerhub'
        dockerComposeFile: '**/docker-compose.yml'
        dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
        projectName: '$(ProjetcName)'        
        additionalImageTags: |
          $(tag)
          latest
        includeSourceTags: true
        includeLatestTag: true        
        action: 'Build services'
        
    - task: DockerCompose@0
      displayName: Push services
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'dockerhub'
        dockerComposeFile: '**/docker-compose.yml'
        dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
        projectName: '$(ProjetcName)'        
        additionalImageTags: |
          $(tag)
          latest
        includeSourceTags: true
        includeLatestTag: true       
        action: 'Push services'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'unifique'
        command: 'push'
        tags: |
          $(tag)
          latest
    

