trigger:
- main

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)    
    steps:    
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'unifique'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    
    