resources:
  repositories:
    - repository: unifique
      type: github
      endpoint: sidneyevpereira
      name: sidneyevpereira/unifique      

trigger:
- main

variables:
  vmImageName: 'ubuntu-latest'
  tag: '$(Build.BuildId)'
  ProjetcName: 'sidneyevpereira/unifique:$(Build.BuildId)'  

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)    
    steps:
    - task: DockerCompose@0
      displayName: Build services
      inputs:
        projectName: $(ProjetcName)         
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'dockerhub'
        dockerComposeFile: '**/docker-compose.yml'        
        additionalImageTags: $(tag)        
        qualifyImageNames: true        
        action: 'Build services'
        buildImages: true
        detached: false

        
    - task: DockerCompose@0
      displayName: Push services
      inputs:
        projectName: $(ProjetcName)        
        containerregistrytype: 'Container Registry'        
        dockerRegistryEndpoint: 'dockerhub'        
        dockerComposeFile: '**/docker-compose.yml'
        additionalImageTags: $(tag)
        includeSourceTags: true
        includeLatestTag: true
        qualifyImageNames: true
        action: 'Push services' 
    

