resources:
  repositories:
    - repository: unifique
      type: github
      endpoint: sidneyevpereira
      name: sidneyevpereira/unifique      

trigger:
- main

variables:
  vmImageName: 'ubuntu-latest'
  tag: '$(Build.BuildId)'
  ProjetcName: 'sidneyevpereira/unifique:$(Build.BuildId)'
  azureContainerRegistry: docker.io
  azureSubscriptionEndpoint: sidneyevpereira/unifique   

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)    
    steps:
    - task: DockerCompose@0
      displayName: Build services
      inputs:
        projectName: $(ProjetcName)         
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'dockerhub'
        dockerComposeFile: '**/docker-compose.yml'        
        additionalImageTags: $(tag)
        qualifyImageNames: true        
        action: 'Build services'
    
    - task: DockerCompose@0
      displayName: Container registry login
      inputs:
        containerregistrytype: Azure Container Registry
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureContainerRegistry: $(azureContainerRegistry)      
        
    - task: DockerCompose@0
      displayName: Push services
      inputs:
        projectName: $(ProjetcName)        
        containerregistrytype: 'Container Registry'        
        dockerRegistryEndpoint: 'dockerhub'        
        dockerComposeFile: '**/docker-compose.yml'
        additionalImageTags: $(tag)
        qualifyImageNames: true
        action: 'Push services'
        workingDirectory: 'unifique'     
    