resources:
  repositories:
    - repository: unifique  
      type: github
      name: sidneyevpereira/unifique
      endpoint:     
      ref: /refs/heads/master

trigger:
- main

variables:
  vmImageName: 'ubuntu-latest'
  tag: '(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)    
    steps:
    - task: DockerCompose@0
      displayName: Build services
      inputs:
        projectName: $(Build.Repository.Name)
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'dockerhub'
        dockerComposeFile: '**/docker-compose.yml'        
        additionalImageTags: $(tag)
        qualifyImageNames: true        
        action: 'Build services'
        
        
    - task: DockerCompose@0
      displayName: Push services
      inputs:
        projectName: $(Build.Repository.Name)        
        containerregistrytype: 'Container Registry'        
        dockerRegistryEndpoint: 'dockerhub'        
        dockerComposeFile: '**/docker-compose.yml'
        additionalImageTags: $(tag)
        qualifyImageNames: true
        action: 'Push services'       
    