trigger:
- main

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'
  tag: '$(Build.BuildId)'

pool:
      vmImage: $(vmImageName)
      
stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      displayName: Build and push an image to container registry
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'dockerhub'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
